    stage ('Dotnet Restore') {
      steps {
        script {
          echo 'Hello World! 5 Jenkins Dentro'
        }
      }
    }

    stage ('Veracode SCA Scan') {
      steps {
        echo 'Hello World! 6'
      }
    }